package com.siel.kernel.model;

/**
 * Data Transfer Object representing the user's reflection survey state.
 * This state is generated by the React frontend and synced to the backend.
 */
public class SurveyState {
    private String cadence;
    private int energy;
    private int social;
    private int stress;
    private String reflection;

    public SurveyState() {}

    public SurveyState(String cadence, int energy, int social, int stress, String reflection) {
        this.cadence = cadence;
        this.energy = energy;
        this.social = social;
        this.stress = stress;
        this.reflection = reflection;
    }

    public String getCadence() { return cadence; }
    public void setCadence(String cadence) { this.cadence = cadence; }

    public int getEnergy() { return energy; }
    public void setEnergy(int energy) { this.energy = energy; }

    public int getSocial() { return social; }
    public void setSocial(int social) { this.social = social; }

    public int getStress() { return stress; }
    public void setStress(int stress) { this.stress = stress; }

    public String getReflection() { return reflection; }
    public void setReflection(String reflection) { this.reflection = reflection; }
}
